- name: dependencies
  hosts: localhost
  vars:
    - docker: false      
  tasks:
    - name: apt
      become: yes
      apt:
        update_cache: yes
        pkg:
          - git
          - curl 
          - wget 
          - unzip 
          - zip
          - jq
          - apt-transport-https
          - ca-certificates
          - gnupg
          - lsb-release
          - fzf
          - software-properties-common
          - tar
          - gnupg2 # https://github.com/drduh/YubiKey-Guide#debian-and-ubuntu
          - gnupg-agent
          - dirmngr
          - cryptsetup
          - scdaemon
          - pcscd
          - hopenpgp-tools
          - yubikey-personalization
          - libssl-dev
          - swig 
          - libpcsclite-dev
          - openvpn
          - freerdp2-x11
          - openconnect
    
    - name: snap idea
      when: not docker
      become: yes
      snap:
        name: intellij-idea-community
        classic: yes


    - name: snap code
      when: not docker
      become: yes
      snap:
        name: code
        classic: yes

    - name: snap
      # snaps rely on systemd initialization so no way for them to work inside docker
      # https://stackoverflow.com/a/58484154/5665181
      when: not docker
      become: yes
      snap:
        name:
          - dbeaver-ce
          - spotify
          - vlc
          - remmina
          - keepassxc
          - gimp
    - name: snap enable usb access for keepass
      when: not docker
      become: yes
      shell: snap connect keepassxc:raw-usb core:raw-usb
        
- name: install bash it
  hosts: localhost
  tasks:
    - script: scripts/bash-it.sh
      args:
        creates: "{{home}}/.bash_it"      

- name: install sdkman tools
  hosts: localhost
  tasks:
    - script: scripts/sdkman.sh
      args:
        creates: "{{home}}/.sdkman"
    - script: scripts/sdkman-tools.sh
      args:
        creates: "{{home}}/.sdkman/candidates/java/current"

- name: install docker
  hosts: localhost
  tasks:
    - script: scripts/docker-install.sh
      become: yes
      args:
        creates: "/usr/bin/docker"

- name: install rust
  hosts: localhost
  tasks:
    - script: scripts/rust-install.sh
      args:
        creates: "/home/flakm/.cargo/bin/rustc"

# For now, I'm just going to manually start it the first time and auth
# and than run systemctl --user enable dropbox 
- name: install dropbox
  hosts: localhost
  vars:
    home: /home/flakm
  tasks:
    - name: Install dropbox
      shell: curl -L "https://www.dropbox.com/download?plat=lnx.x86_64" | tar -C {{home}} -xzf -
      args:
        creates: "{{home}}/.dropbox-dist/dropboxd"


- name: install onedrive
  hosts: localhost
  vars:
    home: /home/flakm  
  tasks:
    - script: scripts/onedrive-install.sh {{home}}
      become: yes
      args:
        creates: "/usr/bin/onedrive"      
# And then mannually:
# onedrive # to provide outh tokens
# systemctl --user enable onedrive
# systemctl --user start onedrive
# systemctl --user status onedrive

- name: install nvm
  hosts: localhost
  tasks:
    - script: scripts/nvm.sh
      args:
        creates: "{{home}}/.nvm/"

- name: install flutter
  hosts: localhost
  vars:
    docker: false
  tasks:
    # https://developer.android.com/studio/install#64bit-libs
    - name: install requirements for android studio 
      become: yes
      apt:
        update_cache: yes
        pkg:
          - libc6:i386
          - libncurses5:i386
          - libstdc++6:i386
          - lib32z1
          - libbz2-1.0:i386
    - script: scripts/android-studio.sh
      become: yes
      args:
        creates: /usr/local/android-studio

    - name: install requirements for kvm acceleration
      become: yes
      apt:
        update_cache: yes
        pkg:
          - qemu-kvm 
          - bridge-utils 
          - libvirt-daemon-system 
          - libvirt-clients

    - name: snap flutter
      when: not docker
      become: yes
      snap:
        name: flutter
        classic: yes              